[versions]
fabric-loom = "1.9-SNAPSHOT"
minecraft = "1.21.1"
fabric-loader = "0.16.10"
parchmentmc-mappings = "2024.11.17"
lombok = "1.18.36"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }